name: Build
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Build
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4g
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew --info --stacktrace :app:assembleDebug
          ./gradlew --info --stacktrace :client:assembleDebug
  ktlint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: false
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx4g
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew ktlintCheck
